### ISSUE TITLE
Some problems with setting up the plugin

### ISSUE THREAD

**Issue by kwerber** [elect86/magik#1]
First of all, I am not that knowledgeable when it comes to gradle, so it is certainly possible that I have missed some things.

I tried using this plugin following the README file but came across two problems:

1. Gradle is unable to build the project when using the `alsoSnapshot()` option
2. Gradle is able to build but unable to publish when not using the `alsoSnapshot()` option

Some links:

- [Error log for the first problem](https://gist.github.com/kwerber/35c72d654dd1ae6710b6da2faab0ec10)
  - Line 31 is `}.alsoSnapshot() // this clones the publication for snapshots`
  - Following the stacktrace, magik most likely has a problem when running `git describe --tags` which outputs `fatal: No names found, cannot describe anything.` which it then attempts to parse to an int in the `gitDistance` function
  - Do I need tags for this to work? There is no mention in the README about that
- [Error log for the second problem](https://gist.github.com/kwerber/acba49cda787ca08f901dbcff624c251)
  - `Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 52: https://api.github.com/repos/kwerber/abc/contents/de\kwerber\abc\0.1\abc-0.1.jar`
  - The illegal character is the first `\`
- [build.gradle.kts for the first problem](https://github.com/kwerber/abc/blob/677d55c9457bf790b2e7f59adfeb49d83327db4e/lib/build.gradle.kts)
- [build.gradle.kts for the second problem](https://github.com/kwerber/abc/blob/ad1d98e8e2c88259f11147becee1cf3a5cc05f23/lib/build.gradle.kts)

Some additional information:

- I am testing this plugin on my https://github.com/kwerber/abc repo (where commit 2 and 3 cause problems 1 and 2)
- Gradle version 7.0.2
- Java openjdk version "16.0.1" 2021-04-20
- and git version 2.31.1.windows.1

**Comment by elect86** [comment]
Hey Kevin,

so, I pushed some additional logic which hopefully will help with your issues

1) Now you don't need tags anymore for this to work, a [`-1` will be returned](https://github.com/elect86/magik/blob/master/plugin/src/main/kotlin/magik/MagikPlugin.kt#L305) if this is the case. 
Moreover, now one can set whatever [postfix he likes best](https://github.com/elect86/magik/blob/master/plugin/src/main/kotlin/magik/MagikPlugin.kt#L285-L286) by passing the ending lambda on `alsoSnapshot`, default is "+$gitDistance"

2) Now all the backslashes will be switched with normal slashes, I haven't test this though

pull version 0.0.5

let me know if these help

**Comment by kwerber** [comment]
Both issues seem to have been fixed, thanks!

**Comment by elect86** [comment]
Nice, thanks for reporting
