### ISSUE TITLE
about gradle-maven-exec-plugin

### ISSUE THREAD

**Issue by insinfo** [elect86/magik#3]
sorry to ask this question around here, but do you intend to release an updated version of gradle-maven-exec-plugin for compatibility with gradle 7.4.1 and java 17 ?

https://github.com/elect86/gradle-maven-exec-plugin

**Comment by elect86** [comment]
No problem,

I'd love to, but I'm submerged from other tasks.. what about I invite you, you try and if you have issues I see what's the problem?

**Comment by elect86** [comment]
I'm gonna close this, if you want to reopen it, feel free to do it
